export const contactEndpoints = [
    { endpoint: "/v1/Contacts/Overview", used: true },
    { endpoint: "/v1/Contacts/CreateContact", used: true },
    { endpoint: "/v1/Contacts/UpdateContact", used: true },
    { endpoint: "/v1/Contacts/DeleteContacts", used: true },
    { endpoint: "/v1/Contacts/AssignContactsToGroups", used: true },
    { endpoint: "/v1/Contacts/DeleteContactsFromContactGroups", used: true },
    { endpoint: "/v1/Contacts/GetCountries", used: false },
    { endpoint: "/v1/Contacts/GetContactUserTypes", used: true },
    { endpoint: "/v1/Contacts/ContactGroupOverview", used: true },
    { endpoint: "/v1/Contacts/CreateContactGroup", used: true },
    { endpoint: "/v1/Contacts/UpdateContactGroup", used: true },
    { endpoint: "/v1/Contacts/DeleteContactGroup", used: true },
    { endpoint: "/v1/Contacts/IsGroupNameDuplicated?newGroupName={groupName}", used: true },
    { endpoint: "/v1/Contacts/UpdateContactsVisibility?visibility={visibility}", used: true },
    { endpoint: "/v1/Contacts/GetSurveyContactFilterOptions/{surveyId}", used: true },
    { endpoint: "/v1/Contacts/IsContactEmailInUse?email={email}", used: false },
    { endpoint: "/v1/Contacts/GetContactsViaEmail?email={email}&exclusionId={exclusionId}", used: true },
    { endpoint: "/v1/Contacts/GetInternalAndExternalContacts/{supplierId}", used: true },
    { endpoint: "/v1/Contacts/GetExternalContacts?supplierId={supplierId}", used: true },
    { endpoint: "/v1/Contacts/GetExternalContactsForGuest?supplierId={supplierId}", used: true },
    { endpoint: "/v1/Contacts/GetExternalPartnerContacts/{supplierId}?includeChildSupplierContacts={includeChildSupplierContacts}", used: true },
    { endpoint: "/v1/Contacts/GetInternalContactsWithUser/{accessTo}", used: true },
    { endpoint: "/v1/Contacts/GetPartnerContactsByModuleType?partnerId={partnerId}&type={type}", used: true },
    { endpoint: "/v1/Contacts/{contactId}/avatar", used: true },
  ];
  