export const ncrEndpoints = [
    { endpoint: "/v1/Ncr/Overview", used: true },
    { endpoint: "/v1/Ncr/{id}", used: true },
    { endpoint: "/v1/Ncr/ncrHoldersContacts", used: false },
    { endpoint: "/v1/Ncr/NcrFields", used: true },
    { endpoint: "/v1/Ncr/{id}/approvalStatusId/{approvalStatusId}", used: true },
    { endpoint: "/v1/Ncr/{id}/ncrHolder/{holderId}", used: true },
    { endpoint: "/v1/Ncr/{id}/removeNcrHolder", used: true },
    { endpoint: "/v1/Ncr/{id}/NextResponsible/{nextResponsible}", used: true },
    { endpoint: "/api/NcrReason/{id}", used: true },
    { endpoint: "/v1/Ncr", used: true },
    { endpoint: "/v1/Ncr/{ncrId}", used: true },
    { endpoint: "/v1/Ncr", used: true },
    { endpoint: "/v1/Ncr/{id}/searchTags", used: true },
    { endpoint: "/v1/Ncr/{ncrId}/CloseNcr", used: true },
    { endpoint: "/v1/Ncr/{ncrId}/OpenNcr", used: true },
    { endpoint: "/api/NcrReason/ReasonsForFilter", used: true },
    { endpoint: "/v1/Ncr/ContactsFilter", used: true },
    { endpoint: "/OwnerContacts/{initialContactId}", used: true },
    { endpoint: "/ExternalOwnerContacts/{supplierId}", used: true },
    { endpoint: "/answer/{actionId}", used: true },
    { endpoint: "/owner/{actionId}/{ownerId}/{ownerType}", used: true },
    { endpoint: "/v1/Ncr/ChangeNCRsVisibility?visibility={visibility}", used: true },
    { endpoint: "/v1/Ncr/CreateReviewOnNcrClosed", used: true },
  ];
  