export const segmentationEndpoints = [
    { endpoint: "/api/SegmentationGroup/GetSegmentationReviewCriteriaGroups", used: true },
    { endpoint: "/api/SegmentationGroup/GetSegmentationReviewCriteria", used: true },
    { endpoint: "/api/SegmentationGroup/RemoveAndCreateReviewCriteria", used: true },
    { endpoint: "/api/SegmentationCategorySetting/GetSegmentationChangeLog?segmentationAlignmentId={alignmentId}", used: true },
    { endpoint: "/api/SegmentationGroup/GetSegmentationActiveAxisCategoryNames", used: true },
    { endpoint: "/v1/Segmentation/GetSegmentationStatusData?from={fromISOString}&to={toISOString}", used: false },
    { endpoint: "/v1/Segmentation/GetSegmentationResultData?from={fromISOString}&to={toISOString}", used: false },
    { endpoint: "/v1/Segmentation/GetFilteredSegmentationStatusData?from={from}&to={to}", used: false },
    { endpoint: "/v1/Segmentation/GetSegmentationResultData?from={from}&to={to}", used: false },
    { endpoint: "/v1/Segmentation/GetSegmentationReportSupplierList", used: true },
    { endpoint: "/v1/Segmentation/GetSavedFiltrationsOnSegmentationByType?filtrationType={filterType}", used: true },
    { endpoint: "/v1/Segmentation/GetSavedFiltrationOnSegmentationById?entityGuidId={id}&filtrationType={filterType}", used: true },
    { endpoint: "/v1/Segmentation/SaveFiltrationOnSegmentation?filterName={encodedFilterName}&filtrationType={filterType}", used: true },
    { endpoint: "/v1/Segmentation/CheckDuplicateFiltration?filterName={encodedFilterName}&filtrationType={filterType}", used: true },
    { endpoint: "/v1/Segmentation/DeleteSavedFiltrationOnSegmentationById?entityGuidId={id}&filtrationType={filterType}", used: true },
    { endpoint: "/v1/Segmentation/GetSegmentationStatusSupplierList", used: false },
    { endpoint: "/v1/Survey/SendRemindersBySegmentationAnalysisId?segmentationAnalysisId={analysisUnitId}", used: true },
    { endpoint: "/v1/Survey/DeleteAnalysisUnit?segmentationAnalysisId={segmentationAnalysisId}", used: true },
    { endpoint: "/v1/Segmentation/AddSegmentHistory", used: true },
    { endpoint: "/v1/Segmentation/UpdateSegmentHistory?manuelSegmentHistoryId={manualSegmentHistoryId}&segmentationCategorySettingId={segmentationCategorySettingId}", used: true },
    { endpoint: "/v1/Segmentation/DeleteSegmentHistory?id={manualSegmentHistoryId}", used: true },
  ];
  