export const partnersEndpoints = [
    { endpoint: "/v1/PartnerGroups?sortByName={sortByName}", used: true },
    { endpoint: "/v1/PartnerGroups", used: true },
    { endpoint: "/v1/PartnerGroups/{groupId}", used: true },
    { endpoint: "/v1/PartnerCategories", used: true },
    { endpoint: "/v1/PartnerCategories/{categoryId}", used: true },
    { endpoint: "/v1/Partners/GetExternalPartners?withEmail={withEmail}&withIsLinked={withIsLinked}&withContacts={withContacts}", used: true },
    { endpoint: "/v1/Partners/GetPartnerList", used: true },
    { endpoint: "/v1/Partners", used: true },
    { endpoint: "/v1/Partners/CreateExternalPartner", used: true },
    { endpoint: "/v1/Partners/IsCompanyNumberInUse?companyNumber={companyNumber}", used: true },
    { endpoint: "/v1/Company/Globalsettings", used: true },
    { endpoint: "/v1/PartnerCategories?{params}", used: true },
    { endpoint: "/v1/PartnerCategories/GetPartnerCategoriesByPartnerId?partnerId={partnerId}&type={type}", used: true },
    { endpoint: "/v1/Partners/{partnerId}", used: true },
    { endpoint: "/v1/Partners/Masterdata/{partnerId}", used: true },
    { endpoint: "/v1/PartnerCustomColumns?sortByName=false", used: true },
    { endpoint: "/Categories", used: true },
    { endpoint: "/Group?GroupId={groupId}", used: true },
    { endpoint: "/v1/Partners/DeletePartners", used: true },
    { endpoint: "/v1/Partners/{parentId}/Children", used: true },
    { endpoint: "/v1/Partners/UnMerge/{parentId}/Children", used: true },
    { endpoint: "/v1/Partners/IsValidMerge/{parentId}/Children", used: true },
    { endpoint: "/v1/Partners/{partnerId}/Unlink", used: true },
    { endpoint: "/v1/Partners/PartnerStatusLog?parentId={partnerId}", used: true },
    { endpoint: "/v1/Partners/Children/{partnerId}", used: false },
    { endpoint: "/v1/Partner/{partnerId}/Children", used: true },
    { endpoint: "/v1/SupplierProfile?supplierId={partnerId}", used: true },
    { endpoint: "/v1/Partner/Comment?partnerId={partnerId}", used: true },
    { endpoint: "/v1/Partner/Comment?partnerId={activityId}", used: false },
    { endpoint: "/v1/Partners/IsOwner?partnerId={partnerId}", used: true },
    { endpoint: "/v1/Partners/UpdatePartnerDomain?partnerId={partnerId}&domain={domain}", used: true },
    { endpoint: "/v1/Partners/{partnerId}", used: true },
    { endpoint: "/v1/Partners/{partnerId}/compliance-contacts", used: true },
    { endpoint: "/v1/Partners/{partnerId}/compliance-contacts-for-guest", used: true },
    { endpoint: "/v1/Partners/{partnerId}/reasons/statistics?from={from}&to={to}", used: true },
  ];
  