export const adminPartnerEndpoints = [
    { endpoint: "/v1/AdminPartner/SetPartnerStatusAsDefault?id={id}", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerStatuses?sortByName={sortByName}", used: true },
    { endpoint: "/v1/AdminPartner/CreatePartnerStatus", used: true },
    { endpoint: "/v1/AdminPartner/DeletePartnerStatuses", used: true },
    { endpoint: "/v1/AdminPartner/UpdatePartnerStatus/{statusId}", used: true },
    { endpoint: "/v1/AdminPartner/StatusEventSettingOverview", used: true },
    { endpoint: "/v1/AdminPartner/CreateStatusEventSetting", used: true },
    { endpoint: "/v1/AdminPartner/UpdateStatusEventSetting", used: true },
    { endpoint: "/v1/AdminPartner/DeleteStatusEventSettings", used: true },
    { endpoint: "/v1/AdminPartner/IsStatusEventSettingInUse", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerGroups", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerCategories?type={type}&sortByName=true", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerCategories?sortByName=true", used: true },
    { endpoint: "/v1/AdminPartner/GetInvitationStatusOverview", used: true },
    { endpoint: "/v1/AdminPartner/DeleteInvitationStatus", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerDataExtractTemplate", used: true },
    { endpoint: "/v1/AdminPartner/GetPartners?sortByName={sortByName}", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerMailTemplate", used: true },
    { endpoint: "/v1/AdminPartner/GetPartnerInviteListOverview", used: true },
    { endpoint: "/v1/AdminPartner/CreateOrUpdatePartnerMailTemplate", used: true },
    { endpoint: "/v1/AdminPartner/SendPartnerEmailInvitations", used: true },
    { endpoint: "/v1/AdminPartner/UploadPartnerFile?fileId={fileId}&overwriteIfBlank={overwriteIfBlank}&baseCurrency={baseCurrency}", used: true },
    { endpoint: "/v1/AdminPartner/PartnerStatusOverview", used: true },
  ];
  