export const adminComplianceEndpoints = [
    { endpoint: "/v1/AdminCompliance/CreateTemplate", used: true },
    { endpoint: "/v1/AdminCompliance/QuestionTypeList", used: true },
    { endpoint: "/v1/AdminCompliance/CustomDropdownList?sortByName={sortByName}", used: true },
    { endpoint: "/v1/AdminCompliance/TemplateGroupList?sortByName={sortByName}", used: true },
    { endpoint: "/v1/AdminCompliance/IsTemplateNameInUse?name={name}", used: true },
    { endpoint: "/v1/AdminCompliance/GetTemplateGroupOverview", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateTemplateGroupOrders?id={id}&oldOrder={oldOrder}&newOrder={newOrder}", used: true },
    { endpoint: "/v1/AdminCompliance/CreateTemplateGroup?name={name}", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateTemplateGroup?id={id}&name={name}", used: true },
    { endpoint: "/v1/AdminCompliance/DeleteTemplateGroups", used: true },
    { endpoint: "/v1/AdminCompliance/IsTemplateGroupInUse?name={name}", used: true },
    { endpoint: "/v1/AdminCompliance/GateKeepersOverview", used: true },
    { endpoint: "/v1/AdminCompliance/GetAllComplianceStatuses", used: true },
    { endpoint: "/v1/AdminCompliance/GetAllActiveTemplates", used: true },
    { endpoint: "/v1/AdminCompliance/GetActiveProductTemplates", used: true },
    { endpoint: "/v1/AdminCompliance/DeleteGateKeepers", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateGateKeeper", used: true },
    { endpoint: "/v1/AdminCompliance/CreateGateKeeper", used: true },
    { endpoint: "/v1/AdminCompliance/TemplatePartnerGroupMatrixOverview", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateTemplatePartnerGroup?templateId={templateId}&groupId={groupId}&isCheck={isCheck}", used: true },
    { endpoint: "/v1/AdminCompliance/SendSelfAssessments", used: true },
    { endpoint: "/v1/AdminCompliance/ComplianceTemplateOverview", used: true },
    { endpoint: "/v1/AdminCompliance/GetTemplateDetailById?id={id}", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateTemplate", used: true },
    { endpoint: "/v1/AdminCompliance/DeleteTemplates", used: true },
    { endpoint: "/v1/AdminCompliance/CopyTemplate?templateId={templateId}&templateName={templateName}", used: true },
    { endpoint: "/v1/AdminCompliance/CopyComplianceRegistrations?oldTemplateId={oldTemplateId}&newTemplateId={newTemplateId}", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateTemplateActivation?active={active}", used: true },
    { endpoint: "/v1/AdminCompliance/GetEnabledScoreComplianceTemplates", used: true },
    { endpoint: "/v1/AdminCompliance/UpdateSupplierProfileComplianceDefaults", used: true },
    { endpoint: "/v1/AdminCompliance/DeleteSupplierProfileComplianceDefaults", used: true },
  ];
  