export const adminReviewEndpoints = [
    { endpoint: "/v1/AdminReview/GetReviewSetting", used: true },
    { endpoint: "/v1/AdminReview/SetReviewSetting", used: true },
    { endpoint: "/v1/AdminReview/GetReviewCategories", used: false },
    { endpoint: "/v1/AdminReview/GetReviewCategoryGroupOverview", used: true },
    { endpoint: "/v1/AdminReview/CreateReviewCategoryGroup?name={name}", used: true },
    { endpoint: "/v1/AdminReview/UpdateReviewCategoryGroup?id={id}&name={name}", used: true },
    { endpoint: "/v1/AdminReview/DeleteReviewCategoryGroups", used: true },
    { endpoint: "/v1/AdminReview/IsReviewCategoryGroupInUse?name={name}", used: true },
    { endpoint: "/v1/AdminReview/GetAllReviewCategoryGroups", used: true },
    { endpoint: "/v1/AdminReview/GetReviewCategoriesCriteriaOverview", used: true },
    { endpoint: "/v1/AdminReview/CreateReviewCategoryCriteria", used: true },
    { endpoint: "/v1/AdminReview/UpdateReviewCategoryCriteria", used: true },
    { endpoint: "/v1/AdminReview/IsReviewCategoryCriteriaNameInUse?name={name}", used: true },
    { endpoint: "/v1/AdminReview/UpdateReviewCategoryCriteriaActivation?activation={activation}", used: true },
    { endpoint: "/v1/AdminReview/UpdateReviewCategoryCriteriaGroup?groupId={groupId}", used: true },
    { endpoint: "/v1/AdminReview/DeleteReviewCategoryCriteria", used: true },
    { endpoint: "/v1/AdminReview/GetSurveyTemplateGroupOverview", used: true },
    { endpoint: "/v1/AdminReview/CreateSurveyTemplateGroup?name={name}", used: true },
    { endpoint: "/v1/AdminReview/UpdateSurveyTemplateGroup?id={id}&name={name}", used: true },
    { endpoint: "/v1/AdminReview/DeleteSurveyTemplateGroups", used: true },
    { endpoint: "/v1/AdminReview/IsSurveyTemplateGroupInUse?name={name}", used: true },
    { endpoint: "/v1/AdminReview/GetAllSurveyTypes", used: false },
    { endpoint: "/v1/AdminReview/GetAllSurveyTemplateGroups", used: true },
    { endpoint: "/v1/AdminReview/CreateSurveyTemplate", used: true },
    { endpoint: "/v1/AdminReview/GetSurveyTemplateOverview", used: true },
    { endpoint: "/v1/AdminReview/DeleteSurveyTemplates", used: true },
    { endpoint: "/v1/AdminReview/UpdateSurveyTemplate", used: true },
    { endpoint: "/v1/AdminReview/GetSurveyTemplateById?id={id}", used: true },
    { endpoint: "/v1/AdminReview/IsSurveyTemplateInUse?name={name}", used: true },
    { endpoint: "/v1/AdminReview/PutCriteriaGroupCategoryRelation/{categoryId}", used: true },
    { endpoint: "/v1/AdminReview/DeleteCriteriaGroupCategoryRelation", used: true },
    { endpoint: "/v1/AdminReview/UpdateSurveyTemplateGroupType?typeId={typeId}", used: true },
    { endpoint: "/v1/AdminReview/UpdateSurveyTemplateGroupType", used: true },
    { endpoint: "/v1/AdminReview/GetDefaultReviewCriteria", used: true },
  ];
  