export const adminCompanyEndpoints = [
    { endpoint: "/v1/AdminCompany/GetCustomDropdowns", used: true },
    { endpoint: "/v1/AdminCompany/CreateCustomDropdown", used: true },
    { endpoint: "/v1/AdminCompany/UpdateCustomDropdown", used: true },
    { endpoint: "/v1/AdminCompany/RemoveCustomDropdowns", used: true },
    { endpoint: "/v1/AdminCompany/GetCompanyInformation", used: true },
    { endpoint: "/v1/AdminCompany?companyId={companyId}", used: true },
    { endpoint: "/v1/AdminCompany/UpdateCompanyLogo?logoPictureId={fileId}", used: false },
    { endpoint: "/v1/AdminCompany/UpdateCompanyLogo", used: false },
    { endpoint: "/v1/AdminCompany/IsCustomDropdownHeadlineDuplicate?headline={headlineText}&id={headlineId}", used: true },
    { endpoint: "/v1/AdminCompany/GetCustomDropdownsInUseStatus", used: true },
    { endpoint: "/v1/AdminCompany/GetCompanySettings", used: true },
    { endpoint: "/v1/AdminCompany/GetCompanyFaqLink", used: true },
    { endpoint: "/v1/AdminCompany/UpdateCompanySettings", used: true },
    { endpoint: "/v1/AdminCompany/GetCompanySettingsPartnerHeadline", used: true },
    { endpoint: "/v1/AdminCompany/SubmitPartnerHeadlines", used: true },
    { endpoint: "/v1/AdminCompany/GetExternalPartnerCustomColumns", used: true },
    { endpoint: "/v1/AdminCompany/SubmitExternalPartnerCustomColumns", used: true },
    { endpoint: "/v1/AdminCompany/IsCustomDropdownOptionInUse?customDropdownOptionId={id}", used: true },
    { endpoint: "/v1/AdminCompany/GetEmbeddedReport", used: false },
    { endpoint: "/v1/AdminCompany/GetEmbeddedReports", used: true },
    { endpoint: "/v1/AdminCompany/CreateOrUpdateEmbeddedReport?id={id}", used: true },
    { endpoint: "/v1/AdminCompany/CreateOrUpdateEmbeddedReport", used: true },
    { endpoint: "/v1/AdminCompany/removeEmbeddedReport?id={id}", used: true },
    { endpoint: "/v1/AdminCompany/GetSummaryReport", used: true },
    { endpoint: "/v1/AdminCompany/AddOrEditSummaryReport", used: true },
    { endpoint: "/v1/AdminCompany/GetRiskReport?riskReportId={riskReportId}", used: true },
    { endpoint: "/v1/AdminCompany/GetRiskReport", used: true },
    { endpoint: "/v1/AdminCompany/AddOrEditRiskReport", used: true },
    { endpoint: "/v1/AdminCompany/RemoveRiskReport?riskReportId={riskReportId}", used: true },
  ];
  